version: "3"

configs:
  cluster-config:
    file: ./config.yaml

x-cluster-db: &cluster-db
  build:
    context: .
    dockerfile: Dockerfile
  configs:
    - cluster-config
  network_mode: host
  environment:
    - CONFIG_PATH=/cluster-config

services:
  cluster-db-1:
    <<: *cluster-db
    command: start cluster-db-1

  cluster-db-2:
    <<: *cluster-db
    command: start cluster-db-2

  cluster-db-3:
    <<: *cluster-db
    command: start cluster-db-3

  cluster-db-4:
    <<: *cluster-db
    command: start cluster-db-4

  cluster-db-5:
    <<: *cluster-db
    command: start cluster-db-5
